kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: customer-pv-claim
  namespace: customer
  labels:
    app: customer-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi