apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-app-env
  namespace: customer
data:
  database-url: customer-pgpool-service
  spring-datasource-url: jdbc:postgresql://customer-pgpool-service/postgres
  jdbc-driver: org.postgresql.Driver
  spring-kafka-bootstrap-servers: kafka-service.kafka:9092
  kafka-topic-name-transfer-amount: transferAmount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
  namespace: customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
        - name: customer-app
          image: vadimstepuro/customer-app:1.0.4
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: customer-app-env
                  key: spring-datasource-url

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: customer-db-secret
                  key: customer-db-root-username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-db-secret
                  key: customer-db-root-password

            - name: JDBC_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: customer-app-env
                  key: jdbc-driver

            - name: JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: customer-app-env
                  key: spring-datasource-url

            - name: JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: customer-db-secret
                  key: customer-db-root-username

            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-db-secret
                  key: customer-db-root-password
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  name: customer-app-env
                  key: spring-kafka-bootstrap-servers
            - name: KAFKA_TOPIC-NAME_TRANSFER-AMOUNT
              valueFrom:
                configMapKeyRef:
                  name: customer-app-env
                  key: kafka-topic-name-transfer-amount
---
apiVersion: v1
kind: Service
metadata:
  name: customer-app-service
  namespace: customer
spec:
  type: NodePort
  selector:
    app: customer-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      nodePort: 30000