kind: PersistentVolume
apiVersion: v1
metadata:
  name: customer-pv-volume
  labels:
    type: local
    app: customer-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/customer-db"